import type { UiLanguage } from './types';
export const COPY = {
  en: {
    settings: 'Settings',
    complexity: 'Complexity',
    sourceWeights: 'Source Weights',
    diagnostic: 'Diagnostic',
    export: 'Export',
    dataSources: 'Data Sources', provider: 'Provider', license: 'License', sourceRepository: 'Source Repository', catalogVersion: 'Catalog Version', acceptedRows: 'Accepted Rows', rejectedRows: 'Rejected Rows', sourceStatus: 'Status', complexityMetric: 'Complexity Metric', sourceReady: 'Ready', sourceFixture: 'Development Fixture', sourceInvalid: 'Invalid',

    resetQueue: 'Reset Queue',
    resetQueueDescription: 'Clear queued observations and start over with the current settings.',
    resettingQueue: 'Resetting…',
    resetQueueError: 'Could not reset the queue',

    playbackSettings: 'Playback Settings',
    playbackSpeed: 'Playback Speed',
    defaultPlaybackRate: 'Default Speed (x)',
    disableAutoplay: 'Disable Audio Autoplay',
    disableAutoplayDescription: 'Do not start audio automatically when a normal observation opens. Resuming after audio finishes is unaffected.',

    target: 'Target',
    spread: 'Spread',
    commonWordReduction: 'Common Word Reduction',
    commonWordReductionDescription:
      'How strongly word commonality shifts complexity. Words more common than average lower a sentence\u2019s complexity; rarer words raise it. 0 uses the plain grapheme count.',
    save: 'Save',
    saving: 'Saving…',
    invalidValues: 'Invalid values',
    count: 'Count',
    exporting: 'Exporting…',
    download: 'Download',
    ready: 'Ready',
    invalidExport: 'Invalid count or export failed',
    close: 'Close',
    back: 'Back',
    language: 'Switch Language',
    yes: 'Yes',
    no: 'No',
    unavailable: 'Unavailable',
    initialFill: 'Initial Fill',
    observationConsumed: 'Observation Consumed',
    chooseExportFormat: 'Choose Export Format',
    epub: 'EPUB',
    epubDescription: 'iPhone / iPad · Apple Books · Interactive · Offline',
    html: 'HTML',
    htmlDescription: 'Browser / Desktop · Interactive · Offline',
    cancel: 'Cancel',
  },
  te: {
    settings: 'అమరికలు',
    complexity: 'సంక్లిష్టత',
    sourceWeights: 'మూల బరువులు',
    diagnostic: 'నిర్ధారణ సమాచారం',
    export: 'ఎగుమతి',
    dataSources: 'డేటా మూలాలు', provider: 'ప్రదాత', license: 'లైసెన్స్', sourceRepository: 'మూల రిపోజిటరీ', catalogVersion: 'క్యాటలాగ్ సంచిక', acceptedRows: 'ఆమోదించిన వరుసలు', rejectedRows: 'తిరస్కరించిన వరుసలు', sourceStatus: 'స్థితి', complexityMetric: 'సంక్లిష్టత ప్రమాణం', sourceReady: 'సిద్ధం', sourceFixture: 'అభివృద్ధి నమూనా', sourceInvalid: 'చెల్లదు',

    resetQueue: 'క్యూ రీసెట్ చేయి',
    resetQueueDescription: 'వరుసలో ఉన్న పరిశీలనలను తొలగించి, ప్రస్తుత అమరికలతో మళ్లీ మొదలుపెట్టండి.',
    resettingQueue: 'రీసెట్ అవుతోంది…',
    resetQueueError: 'క్యూను రీసెట్ చేయలేకపోయాము',

    playbackSettings: 'ప్లేబ్యాక్ అమరికలు',
    playbackSpeed: 'ప్లేబ్యాక్ వేగం',
    disableAutoplay: 'ఆడియో స్వయంచాలక ప్రారంభాన్ని ఆపు',
    disableAutoplayDescription: 'సాధారణ పరిశీలన తెరిచినప్పుడు ఆడియో స్వయంగా మొదలవదు. ఆడియో ముగిసిన తర్వాత తిరిగి కొనసాగడంపై ప్రభావం ఉండదు.',
    defaultPlaybackRate: 'దినెల వేగం (x)',

    target: 'లక్ష్యం',
    spread: 'వ్యాప్తి',
    commonWordReduction: 'సాధారణ పద తగ్గింపు',
    commonWordReductionDescription:
      'పదాల సాధారణత సంక్లిష్టతను ఎంత మార్చాలో నిర్ణయిస్తుంది. సగటు కంటే సాధారణమైన పదాలు వాక్య సంక్లిష్టతను తగ్గిస్తాయి; అరుదైన పదాలు పెంచుతాయి. 0 అంటే కేవలం అక్షర సంఖ్య.',
    save: 'భద్రపరచు',
    saving: 'భద్రపరుస్తోంది…',
    invalidValues: 'చెల్లని విలువలు',
    count: 'సంఖ్య',
    exporting: 'ఎగుమతి అవుతోంది…',
    download: 'డౌన్‌లోడ్',
    ready: 'సిద్ధం',
    invalidExport: 'చెల్లని సంఖ్య లేదా ఎగుమతి విఫలమైంది',
    close: 'మూసివేయి',
    back: 'వెనుక',
    language: 'భాష మార్చు',
    yes: 'అవును',
    no: 'కాదు',
    unavailable: 'అందుబాటులో లేదు',
    initialFill: 'ప్రారంభ నింపుదల',
    observationConsumed: 'పరిశీలన వినియోగం',
    chooseExportFormat: 'ఎగుమతి రూపాన్ని ఎంచుకోండి',
    epub: 'EPUB',
    epubDescription: 'iPhone / iPad · Apple Books · పరస్పర · ఆఫ్‌లైన్',
    html: 'HTML',
    htmlDescription: 'బ్రౌజర్ / డెస్క్‌టాప్ · పరస్పర · ఆఫ్‌లైన్',
    cancel: 'రద్దు',
  },
} as const;
export function t(
  language: UiLanguage,
  key: keyof typeof COPY.en,
): string {
  return COPY[language][key];
}
